name: Java CI with Maven and Update Containers

on:
  push:
    branches: [ master ]

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Increment version in new branch
        uses: ./.github/update-ui-version
        with:
          app_name: synergy-settings-ui
          new_version: 4.1.51
          k8s_path_value: 3.0/values.yaml
          branch: focalpoint_3.0
          repository: YevhenZzz/changing-value-demo
          token: ${{ secrets.PAT_TOKEN }}
