name: Java CI with Maven and Update Containers

on:
  push:
    branches: [ master ]

jobs:
  increment_version:
    runs-on: ubuntu-latest
    env:
      APP_NAME: synergy-settings-api
      NEW_VERSION: 4.1.3
      K8S_PATH_VALUE: 3.0/values.yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          repository: YevhenZzz/changing-value-demo
          ref: focalpoint_3.0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config --global url."https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com
          cat ~/.gitconfig   

      - name: Increment version in new branch
        run: |
          APP_NAME=${{ env.APP_NAME }}
          NEW_VERSION=${{ env.NEW_VERSION }}
          YAML_FILE=${{ env.K8S_PATH_VALUE }}
          
          if grep -q "${APP_NAME}:" ${YAML_FILE}; then
            sed -i "/${APP_NAME}:/,/version:/{s/version: .*/version: $NEW_VERSION/}" ${YAML_FILE}
          
            git add ${YAML_FILE}
            git commit -m "Update ${APP_NAME} version to ${NEW_VERSION}"
            git push origin focalpoint_3.0
          else
            echo "Error: Service ${APP_NAME} not found in ${YAML_FILE}"
            exit 1
          fi
# sadas