name: Increment App-version on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: YevhenZzz/changing-value-demo
          ref: main

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config credential.helper "store --file=.git/credentials"
          echo "https://github.com/YevhenZzz:${{ secrets.PAT_TOKEN }}" > .git/credentials

      - name: Increment version
        run: |
          CURRENT_VERSION=$(grep 'App-version:' k8s/value | awk '{print $2}')
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2] + 1}"
          sed -i "s/App-version: $CURRENT_VERSION/App-version: $NEW_VERSION/" k8s/value

      - name: Commit changes
        run: |
          git add k8s/values/value
          git commit -m "chore: increment App-version"
          git push origin main
