name: Java CI with Maven and Update Containers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: changing-value-demo
          ref: master
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config --global url."https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com
          cat ~/.gitconfig   

      - name: Increment version
        run: |
          CURRENT_VERSION=$(grep 'App-version:' k8s/values/values.yaml | awk '{print $2}')
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          NEW_VERSION="$((VERSION_PARTS[0])).$((VERSION_PARTS[1])).$((VERSION_PARTS[2] + 1))"
          sed -i "s/App-version: $CURRENT_VERSION/App-version: $NEW_VERSION/" k8s/values/values.yaml

      - name: Commit changes
        run: |
          git add k8s/values/values.yaml
          git commit -m "chore: increment App-version"
          git push origin master
#check 123
#changed version of {{app}} from ... to ... 123
