name: Java CI with Maven and Update Containers

on:
  push:
    branches: [ "master" ]

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        env:
          APP_NAME: "bachend-setting"
        uses: actions/checkout@v3.5.2
        with:
          repository: YevhenZzz/changing-value-demo
          ref: master
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config --global url."https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com
          cat ~/.gitconfig   

      - name: Create a new branch
        run: |
          git checkout -b "${{ env.APP_NAME }}-${{ steps.versioning.outputs.version }}"

      - name: Increment version
        run: |
          CURRENT_VERSION=$(grep 'apiVersion:' k8s/charts/offline-configurator/values-dev.yaml | awk '{print $2}')
          NEW_VERSION=${{ steps.versioning.outputs.version }}
          sed -i "s/apiVersion: $CURRENT_VERSION/apiVersion: $NEW_VERSION/" k8s/charts/offline-configurator/values-dev.yaml

      - name: Commit and push changes
        run: |
          git add k8s/charts/offline-configurator/values-dev.yaml
          git commit -m "Change api version from $CURRENT_VERSION to $NEW_VERSION"
          git push origin "${{ env.APP_NAME }}-${{ steps.versioning.outputs.version }}"

      - name: Create pull request
        run: |
          gh pr create -B main -H "${{ env.APP_NAME }}-${{ steps.versioning.outputs.version }}" 
          --title 'Update api version'
          --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
#sadasd
