name: Java CI with Maven and Update Containers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update Version and Send Pull Request
        run: |
          # Extract the latest version from your Maven project
          LATEST_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          # Set repository details
          REPOSITORY="YevhenZzz/changing-value-demo"
          FOLDER="k8s/values"
          BRANCH_NAME="backend-syner:$LATEST_VERSION"

          # Clone the remote repository and change working directory
          git clone \
            --depth=1 \
            --branch=master \
            https://github.com/$REPOSITORY \
            $FOLDER

          cd $FOLDER

          # Update the version in the file (replace with your logic)
          sed -i "s/App-version: .*/App-version: $LATEST_VERSION/" your-file.yaml

          # Commit the changes
          git add .
          git commit -m "chore: update version to $LATEST_VERSION"
          git push origin $BRANCH_NAME

          # Authorize GitHub CLI for the current repository and
          # create a pull request containing the updates.
          gh auth login --with-token < token.txt
          gh pr create \
            --body "" \
            --title "chore: update version to $LATEST_VERSION" \
            --head "$BRANCH_NAME" \
            --base "master"
